name: Node.js Package

on:
  push:
    branches:
      - master

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: ${{ (github.ref != format('refs/heads/{0}', github.event.repository.default_branch)) }}

jobs:
  publish-gpr:
    uses: SohoHouse/github-actions/.github/workflows/build_code.yml@v1
    secrets: inherit
    with:
      image: node:20
      cache_folders: |
        node_modules
      save_artifacts: |
        dist
      commands: |
        echo "_auth = $NPM_AUTH" >> .npmrc
        yarn install --frozen-lockfile
        echo "----------------yarn ci----------------"
        yarn --ci
        echo "---------------yarn publish---------------"
        npm config set registry "https://nexus.infra.sohohousedigital.com/repository/npm-private/"
        if [ "${{ github.ref }}" = "${{ format('refs/heads/{0}', github.event.repository.default_branch) }}" ]; then
          echo "publish package"
          yarn publish
        else
          echo "there is no need to publish package from feature branch"
        fi

  # publish-gpr-old:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         registry-url: https://npm.pkg.github.com/sohohouse
  #     - run: yarn --ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}